env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/all
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
  - plugin:react/jsx-runtime
  - plugin:jsdoc/recommended-typescript-error
  - plugin:promise/recommended
  - plugin:playwright/recommended
  - plugin:security/recommended
  - plugin:perfectionist/recommended-natural
  - plugin:array-func/all
  - plugin:no-unsanitized/DOM
  - plugin:react-perf/all
  - plugin:react-form-fields/recommended
  - plugin:ssr-friendly/recommended
  - plugin:react-hook-form/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:import/errors
overrides:
  - env:
      node: true
    files:
      - "*.ts"
      - "*.tsx"
      - "*.js"
    parserOptions:
      sourceType: module
parser: "@typescript-eslint/parser"
parserOptions:
  extraFileExtensions:
    - ".yaml"
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: ./
root: true
ignorePatterns:
  - node_modules/
  - .eslintrc.yaml
  - .prettierrc.yaml
  - .vscode/
  - .github/
  - .gitignore
  - .gitattributes
  - .git/
  - .husky/
  - .lintstagedrc.yaml
  - .prettierignore
  - panda.config.ts
  - README.md
  - pnpm-lock.yaml
  - playwright.config.ts
  - tsconfig.json
  - tsconfig.node.json
  - vite.config.ts
  - vitest.config.ts
  - index.html
  - postcss.config.cjs
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - jsx-a11y
  - prettier
  - react-refresh
  - jsx-a11y
  - import
  - jsdoc
  - promise
  - testing-library
  - perfectionist
  - array-func
  - no-unsanitized
  - react-perf
  - react-form-fields
  - ssr-friendly
  - validate-jsx-nesting
  - react-hook-form
settings:
  react:
    version: detect
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - "./tsconfig.json"
    node:
      project:
        - "./tsconfig.node.json"
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .jsx
        - .ts
        - .tsx
  react/jsx-max-depth:
    - error
    - max: 5
  react-refresh/only-export-components: 2
  import/no-default-export: error
  import/prefer-default-export: "off"
  prefer-const: error
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
      arrowComponents: arrow-function
  func-style:
    - error
    - expression
    - allowArrowFunctions: true
  func-names:
    - error
    - never
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: false
  no-mixed-spaces-and-tabs: warn
  "@typescript-eslint/consistent-type-definitions":
    - error
    - type
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  react/require-default-props: "off"
  react/jsx-props-no-spreading: "off"
  prettier/prettier:
    - error
    - endOfLine: lf
  "@typescript-eslint/no-misused-promises":
    - error
    - checksVoidReturn: false
  "@typescript-eslint/no-floating-promises":
    - off
  import/no-cycle: "off"
  "@typescript-eslint/consistent-type-imports": "error"
  "@typescript-eslint/strict-boolean-expressions": "error"
  "@typescript-eslint/restrict-template-expressions": "error"
  "@typescript-eslint/restrict-plus-operands": "error"
  "import/no-unresolved": error
  react/jsx-no-literals: off
  react/jsx-no-bind: warn
  no-console: warn
  no-unused-vars: error
  "@typescript-eslint/no-unused-vars": error
  testing-library/await-async-query: error
  testing-library/no-await-sync-query: error
  testing-library/no-debugging-utils: warn
  testing-library/no-dom-import: off
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  no-unsanitized/method: error
  no-unsanitized/property: error
  react-form-fields/no-mix-controlled-with-uncontrolled: error
  react-form-fields/no-only-value-prop: error
  validate-jsx-nesting/no-invalid-jsx-nesting: error
  react/forbid-component-props: off
  react/no-multi-comp: off
